spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/g_38_jp_shop
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: rootrs
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true
  mail:
    username: rslan.mailer@gmail.com
    password: wikvjpxsqelzbjop
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com
key:
  access: 8yNLSHtdF0TL9ncU7u7grovQeXckLJERFqzrYgsc9ug=
  refresh: rGK1pQoGDSfbVs8Y/Vu45sGYQVVP8VFUumXrAhvEq7k=

logging:
  file:
    name: logs/log.log
  level:
    root: info

messages:
  hello: Hello from local application!

