spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/g_38_jp_shop
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: rootrs
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
